// <auto-generated />
using CopAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CopAPI.Migrations.actor
{
    [DbContext(typeof(actorContext))]
    partial class actorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CopAPI.Models.actor", b =>
                {
                    b.Property<int>("act_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("act_fname")
                        .HasColumnType("text");

                    b.Property<string>("act_gender")
                        .HasColumnType("text");

                    b.Property<string>("act_lname")
                        .HasColumnType("text");

                    b.HasKey("act_id");

                    b.ToTable("actors");
                });
#pragma warning restore 612, 618
        }
    }
}
