// <auto-generated />
using CopAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CopAPI.Migrations.movie_cast
{
    [DbContext(typeof(movie_castContext))]
    partial class movie_castContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CopAPI.Models.movie_cast", b =>
                {
                    b.Property<int>("act_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("mov_id")
                        .HasColumnType("integer");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.HasKey("act_id");

                    b.ToTable("movie_casts");
                });
#pragma warning restore 612, 618
        }
    }
}
